<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon />
    <StartupObject>SiteYonetim.UI.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SiteYonetim.Business\SiteYonetim.Business.csproj" />
    <ProjectReference Include="..\SiteYonetim.Data\SiteYonetim.Data.csproj" />
    <ProjectReference Include="..\SiteYonetim.Core\SiteYonetim.Core.csproj" />
  </ItemGroup>

</Project>
